# Generated by Django 4.0.4 on 2022-05-04 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Materials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('resources', models.FileField(upload_to='')),
                ('cover', models.ImageField(upload_to='')),
                ('uploaded_date', models.DateTimeField(auto_now=True)),
                ('years', models.CharField(choices=[('1', 'First Year'), ('2', 'Second Year'), ('3', 'Third Year'), ('4', 'Fourth Year'), ('5', 'FiFth Year')], max_length=1)),
                ('department', models.CharField(choices=[('M', 'Mechanical Engineering'), ('S', 'Software Engineering'), ('C', 'civil Engineering'), ('B', 'Biomedical Engineering'), ('E', 'Electrical Engineering'), ('CH', 'Chemical Engineering')], default=None, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materialResource.materials')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materialResource.materials')),
            ],
        ),
    ]
