# Generated by Django 4.0.4 on 2022-05-04 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('materialResource', '0002_material_alter_comment_material_alter_reply_material_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reply',
            name='material',
        ),
        migrations.AddField(
            model_name='reply',
            name='Comment',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='materialResource.comment'),
        ),
    ]
