# Generated by Django 4.0.4 on 2022-05-04 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('materialResource', '0003_remove_reply_material_reply_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedBack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='materialResource.material')),
            ],
        ),
        migrations.AlterField(
            model_name='reply',
            name='Comment',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='materialResource.feedback'),
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
