# Generated by Django 4.0.4 on 2022-05-08 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('materialResource', '0004_feedback_alter_reply_comment_delete_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('pdf', models.FileField(upload_to='')),
                ('video', models.FileField(upload_to='')),
                ('syllbus', models.FileField(upload_to='')),
                ('uploaded_date', models.DateTimeField(auto_now=True)),
                ('years', models.CharField(choices=[('1', 'First Year'), ('2', 'Second Year'), ('3', 'Third Year'), ('4', 'Fourth Year'), ('5', 'FiFth Year')], max_length=1)),
                ('department', models.CharField(choices=[('M', 'Mechanical Engineering'), ('S', 'Software Engineering'), ('C', 'civil Engineering'), ('B', 'Biomedical Engineering'), ('E', 'Electrical Engineering'), ('CH', 'Chemical Engineering')], default=None, max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='Reply',
        ),
        migrations.AlterField(
            model_name='feedback',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='materialResource.course'),
        ),
        migrations.DeleteModel(
            name='Material',
        ),
    ]
