# Generated by Django 4.0.4 on 2022-06-01 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materialResource', '0005_course_delete_reply_alter_feedback_material_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='pdf',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='course',
            name='syllbus',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='course',
            name='video',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
