# Generated by Django 4.0.5 on 2022-06-03 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materialResource', '0012_student_email_student_user_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='student',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='student',
        ),
    ]
