# Generated by Django 4.0.5 on 2022-06-04 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materialResource', '0014_course_student_feedback_student_delete_student'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='student',
            new_name='users',
        ),
        migrations.RenameField(
            model_name='feedback',
            old_name='student',
            new_name='users',
        ),
    ]
