# Generated by Django 4.0.5 on 2022-06-04 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_customeuser_student_delete_user'),
        ('materialResource', '0015_rename_student_course_users_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='syllbus',
        ),
        migrations.AlterField(
            model_name='course',
            name='users',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.student'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='users',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.student'),
        ),
    ]
