# Generated by Django 4.0.5 on 2022-06-04 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_customeuser_student_delete_user'),
        ('materialResource', '0016_remove_course_syllbus_alter_course_users_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='users',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.student'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='users',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.student'),
        ),
    ]
