# Generated by Django 4.0.5 on 2022-06-05 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materialResource', '0019_course_student_feedback_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='student',
        ),
    ]
