# Generated by Django 4.0.5 on 2022-06-05 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_student_email_remove_student_password_and_more'),
        ('materialResource', '0020_remove_feedback_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='student',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.student'),
            preserve_default=False,
        ),
    ]
