# Generated by Django 4.0.5 on 2022-06-04 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_customeuser_student_delete_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='email',
        ),
        migrations.RemoveField(
            model_name='student',
            name='username',
        ),
    ]
