# Generated by Django 4.0.5 on 2022-06-05 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_student_email_student_password_student_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='email',
        ),
        migrations.RemoveField(
            model_name='student',
            name='password',
        ),
        migrations.RemoveField(
            model_name='student',
            name='username',
        ),
    ]
